### ISSUE TITLE
Question over MVC Compatibility choice

### ISSUE THREAD

**Issue by david-mclean** [ishahrier/ExicoShopifyFramework#13]
In startup.cs the compatibility is set to Version_2_1 but all references are to 2.2. So I was wondering if there is a reason for the compatibility to the set to 2.1? 

If changed to 2.2 is still runs as far as I can tell but Ive not tested all routes.

**Comment by ishahrier** [comment]
The project was first done in 2.1 then got updated in 2.2. i believe that line of code is the remnant of 2.1 project template. I believe changing it to 2.2 should work....

**Comment by david-mclean** [comment]
It does work, I just wanted to make sure it wasnt like that for a particular reason. Thanks
