### ISSUE TITLE
Where is the full documentation ?

### ISSUE THREAD

**Issue by orney21d** [ishahrier/ExicoShopifyFramework#14]
Hi, before all thanks for the great job...

I would like to know where is the full documentation cause almost everything is in a "WIP".

Thanks in advance.

**Comment by ishahrier** [comment]
I am not finding enough time to write them. however i suggest you go over the quick intro. that wiki explains a lot.

**Comment by ishahrier** [comment]
wrote a new wiki page on plan/subscription.
https://github.com/ishahrier/ExicoShopifyFramework/wiki/Subscriptions,Plans-and-Features-Management
